# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJ0N4Dc6GnQUndy0BuC0sv1EtzuS9NbE
"""

import yfinance as yf
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import time

# (구글 시트 연결 부분은 동일)
# ... [연결 설정 코드] ...

def start_analysis():
    sheet.clear()
    # 항목 확장: 진입가 전략, 목표가, 손절가, AI 신호
    headers = ["종목", "현재가", "RSI", "기술적 분석(AI)", "진입 적정가", "매도가(목표)", "손절가"]
    sheet.append_row(headers)

    for theme_name, tickers in themes.items():
        for ticker in tickers:
            try:
                stock = yf.Ticker(ticker)
                df = stock.history(period="6mo") # 6개월 데이터로 세밀 분석
                info = stock.info

                price = df['Close'].iloc[-1]
                rsi = ta.rsi(df['Close'], length=14).iloc[-1]
                ma20 = df['Close'].rolling(window=20).mean().iloc[-1] # 20일 이동평균선

                # 딥 분석 로직
                entry_price = price if rsi <= 35 else "-"
                target_price = info.get('targetMeanPrice', price * 1.15) # 목표가 없으면 15% 상향
                stop_loss = price * 0.95 # 기본 -5% 손절 라인

                # AI 신호 고도화
                if rsi <= 35 and price < ma20:
                    analysis = "강력매수(저점매집구간)"
                elif rsi <= 35:
                    analysis = "매수(단기과매도)"
                elif rsi >= 65:
                    analysis = "매도대기(과열구간)"
                else:
                    analysis = "관망"

                row = [ticker, f"${price:.2f}", round(rsi, 2), analysis,
                       f"${entry_price:.2f}" if entry_price != "-" else "-",
                       f"${target_price:.2f}", f"${stop_loss:.2f}"]
                sheet.append_row(row)
                time.sleep(1)
            except: continue
    print("✨ 딥 분석 완료!")

start_analysis()
