name: Daily Stock Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 8 * * *'
    - cron: '30 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread oauth2client
          pip install git+https://github.com/twopirllc/pandas-ta.git
      - name: Run script
        run: python analysis.py
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
