name: Daily Stock Analysis

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'    # 한국 시간 09:00
    - cron: '0 8 * * *'    # 한국 시간 17:00
    - cron: '30 13 * * *'  # 한국 시간 22:30


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread oauth2client
      - name: Run script
        run: python analysis.py
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
