name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 0 * * *'    # 한국시간 09시
    - cron: '0 8 * * *'    # 한국시간 17시
    - cron: '30 13 * * *'  # 한국시간 22시 30분

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install yfinance pandas_ta gspread oauth2client
      - name: Run script
        run: python analysis.py
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
